PLAT-71: Truncate the task role name_prefix is len() > 32
mergermarket/tf_ecs_task_definition_with_task_role pull request #3
Opened 2017-06-09 16:30 UTC by keymon

In order to avoid an error like this:

* module.lambda_s3_backup.module.s3_backup_taskdef.aws_iam_role.task_role:
  "name_prefix" cannot be longer than 32 characters, name is limited to 64

We replace the name prefix with a truncated + a hash version.

2017-06-09 16:49 UTC, bart613 requested changes
Can we have a test to cover this case?

2017-06-12 11:21 UTC, keymon commented
> Can we have a test to cover this case?

Sure!

2017-06-12 11:48 UTC, keymon commented
@bart613 done

2017-06-12 12:18 UTC, bart613 approved these changes

2017-06-12 12:36 UTC, merged